/**
 * @returns {String} generated comment with date
 */
const getGeneratedFileWarning = () =>
  [
    "/**",
    "* DO NOT EDIT",
    `* Generated by style-dictionary on ${new Date()}`,
    "* github.com/narmi/design_system/",
    "*/\n\n",
  ].join("\n");

const formats = [
  {
    name: "custom/es6-nested",
    formatter: ({ dictionary }) => {
      const nestedProperties = dictionary.allProperties.reduce(
        (result, property) => {
          const { attributes, value } = property;
          const { category, type, item } = attributes;

          if (!(category in result)) {
            result[category] = {};
          }

          if (!(type in result[category])) {
            result[category][type] = {};
          }

          result[category][type][item] = value;

          return result;
        },
        {}
      );

      return [
        getGeneratedFileWarning(),
        `const tokens = ${JSON.stringify(nestedProperties, null, 2)};`,
        "\nmodule.exports = tokens;",
      ].join("\n");
    },
  },
];

module.exports = formats;
