/**
 * @returns {String} generated comment with date
 */
const getGeneratedFileWarning = () =>
  [
    "/**",
    "* DO NOT EDIT",
    `* Generated by style-dictionary on ${new Date()}`,
    "* github.com/narmi/design_system/",
    "*/\n\n",
  ].join("\n");

/**
 * Each one of these `formats` items describes a file output for design tokens.
 * Additional items may be added if a consumer requires a new format.
 */
const formats = [
  {
    name: "custom/es6-nested",
    formatter: ({ dictionary }) => {
      const nestedProperties = dictionary.allProperties.reduce(
        (result, property) => {
          const { attributes, value } = property;
          const { category, type, item } = attributes;

          if (!(category in result)) {
            result[category] = {};
          }

          if (!(type in result[category])) {
            result[category][type] = {};
          }

          result[category][type][item] = value;

          return result;
        },
        {},
      );

      return [
        getGeneratedFileWarning(),
        `const tokens = ${JSON.stringify(nestedProperties, null, 2)};`,
        "\nmodule.exports = tokens;",
      ].join("\n");
    },
  },
  {
    name: "javascript/es6-exports",
    formatter: ({ dictionary }) => {
      return [
        getGeneratedFileWarning(),
        ...dictionary.allProperties.map((token) => {
          let value = JSON.stringify(token.value);
          return `export const ${token.name} = ${value};`;
        }),
      ].join("\n");
    },
  },
  {
    name: "custom/es6-nested-exports",
    formatter: ({ dictionary }) => {
      const nestedProperties = dictionary.allProperties.reduce(
        (result, property) => {
          const { attributes, value } = property;
          const { category, type, item } = attributes;

          if (!(category in result)) {
            result[category] = {};
          }

          if (!(type in result[category])) {
            result[category][type] = {};
          }

          result[category][type][item] = value;

          return result;
        },
        {},
      );

      const exports = Object.keys(nestedProperties).map(
        (category) =>
          `export const ${category} = ${JSON.stringify(nestedProperties[category], null, 2)};`,
      );

      return [getGeneratedFileWarning(), ...exports].join("\n");
    },
  },
];

module.exports = formats;
