# Configuration for zizmor, the GitHub Actions security auditor.
# https://docs.zizmor.sh/configuration/

rules:
  artipacked:
    ignore:
      - release-backport.yaml:75
  obfuscation:
    ignore:
      - chromatic-pr.yaml:111
      - chromatic-pr.yaml:113
