import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=221%3A20562",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      kind: figma.enum("Type", {
        Split: "plain",
      }),
      // No matching props could be found for these Figma properties:
      // "slot": figma.instance('slot'),
      // "elevated": figma.boolean('elevated'),
      // "selection": figma.enum('selection', {
      //   "default": "default",
      //   "highlighted": "highlighted",
      //   "selected": "selected"
      // }),
      // "bleed": figma.boolean('bleed'),
      // "padding": figma.enum('padding', {
      //   "x1": "x1",
      //   "x2": "x2",
      //   "x4": "x4",
      //   "x6": "x6",
      //   "none": "none"
      // })
    },
    example: (props) => <Index kind={props.kind} />,
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=221%3A6332",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      kind: figma.enum("Type", {
        Split: "plain",
      }),
      // No matching props could be found for these Figma properties:
      // "heading": figma.string('Heading'),
      // "showHeading": figma.boolean('Show Heading'),
      // "paragraph": figma.string('Paragraph'),
      // "mobileVersion": figma.boolean('Mobile Version')
    },
    example: (props) => <Index kind={props.kind} />,
  },
);
