import React from "react";
import { AutocompleteModalProps } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AutocompleteModalProps,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A24462",
  {
    props: {
      type: figma.enum("Type", {
        Default: "default",
        CTA: "cta",
        "With save option": "with-save-option",
        Advanced: "advanced",
        "Buttons & categories": "buttons---categories",
      }),
    },
    example: (props) => <AutocompleteModalProps />,
  },
);
