import React from "react";
import Chip from "./index";
import figma from "@figma/code-connect";

import type { VALID_KINDS } from "./index";
import type { IconName } from "../types/Icon.types";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Chip,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=370%3A5171",
  {
    props: {
      kind: figma.enum("Type", {
        Warn: "warn",
        Brand: "primary",
        Info: "info",
        Success: "success",
        Error: "error",
      }) as (typeof VALID_KINDS)[number],
      label: "Button text",
      /*
      startIcon: figma.boolean("Show left icon", {
        true: figma.instance<string>("Left icon"),
        false: undefined,
      }),
      startIcon: figma.boolean("Show right icon", {
        true: figma.instance<string>("Right icon"),
        false: undefined,
      }),
      */
      // number + showNumber
      count: 5,
      // TODO: size unimplemented
    },
    example: (props) => (
      <Chip kind={props.kind} label={props.label} count={props.count} />
    ),
  },
);
