import React from "react";
import Chip from "./index";
import figma from "@figma/code-connect";

import type { VALID_KINDS } from "./index";
import type { IconName } from "../types/Icon.types";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Chip,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=370%3A5171",
  {
    props: {
      kind: figma.enum("Type", {
        Warn: "warn",
        Brand: "primary",
        Info: "info",
        Success: "success",
        Error: "error",
      }) as (typeof VALID_KINDS)[number],
      label: figma.boolean("Label", {
        true: "Label Text",
        false: "",
      }),
      startIcon: figma.boolean("Show StartIcon", {
        true: figma.instance<string>("StartIcon"),
        false: undefined,
      }),
      endIcon: figma.boolean("Show EndIcon", {
        true: figma.instance<string>("EndIcon"),
        false: undefined,
      }),
      count: figma.boolean("Show Count", {
        true: 5,
        false: undefined,
      }),
      isDismissible: figma.boolean("CloseButton"),
      onDismiss: figma.boolean("CloseButton", {
        true: () => {},
        false: undefined,
      }),
      // [UI REFRESH] We must implement "Size" props in code.
      // <https://linear.app/narmi/issue/NDS-2218/chipbadge-add-size-support-and-map-new-prop-names>
    },
    example: ({ kind, count, label }) => (
      <Chip kind={kind} label={label} count={count} />
    ),
  },
);
