import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A23607",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Text"),
      kind: figma.enum("type", {
        info: "info",
        success: "success",
        warning: "warn",
        error: "error",
      }),
      startIcon: figma.enum("prefix-icon", {
        yes: "eye",
      }),
      endIcon: figma.enum("prefix-icon", {
        yes: "eye",
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "suffixicon": figma.boolean('suffix-icon'),
      // "counter": figma.boolean('counter')
    },
    example: (props) => (
      <Index
        label={props.label}
        kind={props.kind}
        startIcon={props.startIcon}
        endIcon={props.endIcon}
      />
    ),
  },
);
