import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=23%3A1415",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      defaultChecked: figma.boolean("Checked"),
      checked: figma.boolean("Checked"),
      disabled: figma.enum("Status", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Empty": "empty",
      //   "Hover": "hover",
      //   "Selected": "selected",
      //   "Error": "error"
      // }),
      // "type": figma.enum('Type', {
      //   "Single": "single",
      //   "Multiple": "multiple"
      // })
    },
    example: (props) => (
      <Index
        defaultChecked={props.defaultChecked}
        checked={props.checked}
        disabled={props.disabled}
      />
    ),
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A14366",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      defaultChecked: figma.boolean("Checked"),
      checked: figma.boolean("Checked"),
      disabled: figma.enum("Status", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('Type', {
      //   "Checkbox input": "checkbox-input",
      //   "Radio input": "radio-input"
      // }),
      // "size": figma.enum('Size', {
      //   "base": "base",
      //   "Default": "default"
      // })
    },
    example: (props) => (
      <Index
        defaultChecked={props.defaultChecked}
        checked={props.checked}
        disabled={props.disabled}
      />
    ),
  },
);
