import React from "react";
import Checkbox from "./";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=364%3A3139",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.enum("Property 1", {
        Checked: true,
      }),
      disabled: figma.enum("Property 1", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper Text'),
      // "card": figma.boolean('Card')
    },
    example: (props) => (
      <Checkbox checked={props.checked} disabled={props.disabled} />
    ),
  },
);
