import React from "react";
import Checkbox from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=364%3A3139",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.enum("Property 1", {
        Checked: true,
      }),
      disabled: figma.enum("Property 1", {
        Disabled: true,
      }),
      kind: figma.boolean("Card", {
        true: "card",
        false: "normal",
      }),
      hasError: figma.enum("Property 1", {
        Error: true,
        Checked: false,
        Disabled: false,
        Default: false,
      }),
    },
    example: ({ checked, disabled, kind, hasError }) => (
      // Checkbox does not currently support Helper Text
      // Support may be added in the future via a `renderLabel` prop
      <Checkbox
        checked={checked}
        disabled={disabled}
        kind={kind}
        hasError={hasError}
      />
    ),
  },
);
