import React from "react";
import { DialogProps } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DialogProps,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=223%3A5592",
  {
    props: {
      type: figma.enum("Type", {
        Info: "info",
        Popup: "popup",
        "Sign In": "sign-in",
        "Create product": "create-product",
        "With radio inputs": "with-radio-inputs",
        "With timeline": "with-timeline",
        "With progress bar": "with-progress-bar",
        "With list": "with-list",
        OTP: "otp",
        Share: "share",
      }),
    },
    example: (props) => <DialogProps />,
  },
);
