import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A24130",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      text: figma.string("Text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "type": figma.enum('Type', {
      //   "Default": "default"
      // }),
      // "position": figma.enum('Position', {
      //   "Top": "top",
      //   "Bottom": "bottom",
      //   "Left": "left",
      //   "Right": "right"
      // })
    },
    example: (props) => <Index text={props.text} />,
  },
);
