import React from "react";
import Count from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Count,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=554%3A6479",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      kind: figma.enum("Kind", {
        Info: "info",
        Success: "success",
        Warn: "warn",
        Error: "error",
        Theme: "theme",
      }),
    },
    example: (props) => <Count value={1} kind={props.kind} />,
  },
);
