import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=965%3A1859",
  {
    props: {
      showTitle: figma.boolean("Show Title"),
      showDescription: figma.boolean("Show Description"),
      title: figma.string("Title"),
      description: figma.string("Description"),
      status: figma.instance("Status"),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        disabled: "disabled",
        active: "active",
        "Status Text": "status-text",
      }),
    },
    example: (props) => <Index />,
  },
);
