import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A10574",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        xs: "xs",
        sm: "m",
      }),
      startIcon: figma.enum("Icon only", {
        False: "pause",
        True: "truck",
      }),
      endIcon: figma.enum("Icon only", {
        False: "pause",
        True: "truck",
      }),
      // No matching props could be found for these Figma properties:
      // "showText": figma.boolean('Show text'),
      // "buttonText": figma.string('Button text'),
      // "showLeftIcon": figma.boolean('Show left icon'),
      // "leftIconStyle": figma.instance('Left icon style'),
      // "rightIconStyle": figma.instance('Right icon style'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "iconStyle": figma.instance('Icon Style'),
      // "logo": figma.instance('Logo'),
      // "color": figma.enum('Color', {
      //   "Brand": "brand",
      //   "Secondary": "secondary",
      //   "Tertiary": "tertiary",
      //   "Success": "success",
      //   "Danger": "danger",
      //   "Warning": "warning",
      //   "Dark": "dark",
      //   "Ghost": "ghost"
      // }),
      // "outline": figma.boolean('Outline'),
      // "logoInside": figma.boolean('Logo inside')
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        size={props.size}
        startIcon={props.startIcon}
        endIcon={props.endIcon}
      />
    ),
  },
);
