import { resolve } from "path";
import { readFileSync, writeFileSync } from "fs";

const TYPE_DEF_DIR = resolve(process.cwd(), "src/types");
const FILE_ICON_SELECTION = resolve(process.cwd(), "src/icons/selection.json");

const iconNames = JSON.parse(
  readFileSync(FILE_ICON_SELECTION).toString()
).icons.map((icon) => icon.properties.name);

const getTypeContent = (iconNames = []) => `
/**
 * Generated by \`scripts/buildTypes.mjs\`
 */
export type IconName =
${iconNames.map((name) => `\t| "${name}"`).join("\n")}
;
`;

writeFileSync(`${TYPE_DEF_DIR}/Icon.types.ts`, getTypeContent(iconNames));
