import React from "react";
import Index, { AvatarProps } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A17356",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Text"),
      size: figma.enum("Size", {
        xs: "xs",
        sm: "m",
      }),
      kind: figma.enum("Type", {
        "With remove button": "tonal",
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "user": figma.enum('User', {
      //   "Jese Leos": "jese-leos",
      //   "Bonnie Green": "bonnie-green",
      //   "Roberta Casas": "roberta-casas",
      //   "Neil Sims": "neil-sims",
      //   "Thomas Lean": "thomas-lean",
      //   "Micheal Gough": "micheal-gough",
      //   "Helene Engels": "helene-engels",
      //   "Lana Byrd": "lana-byrd",
      //   "Leslie Livingston": "leslie-livingston",
      //   "Karen Nelson": "karen-nelson",
      //   "Robert Brown": "robert-brown",
      //   "Joseph McFall": "joseph-mcfall",
      //   "Placeholder image": "placeholder-image"
      // })
    },
    example: (props) => (
      <Index label={props.label} size={props.size} kind={props.kind} />
    ),
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AvatarProps,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=219%3A17803",
  {
    props: {
      status: figma.enum("Status", {
        Online: "online",
        Offline: "offline",
        Alternative: "alternative",
      }),
      size: figma.enum("Size", {
        xs: "xs",
        sm: "sm",
        base: "base",
        lg: "lg",
        xl: "xl",
      }),
    },
    example: (props) => <AvatarProps />,
  },
);
