import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=218%3A4000",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showAlertHeading": figma.boolean('Show alert heading'),
      // "showLeftIcon": figma.boolean('Show left icon'),
      // "rightIconStyle": figma.instance('Right icon style'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "bodyText": figma.string('Body text'),
      // "showBodyText": figma.boolean('Show body text'),
      // "headingText": figma.string('Heading text'),
      // "leftIconStyle": figma.instance('Left icon style'),
      // "text": figma.string('Text'),
      // "type": figma.enum('Type', {
      //   "Complex": "complex",
      //   "Default": "default",
      //   "Small": "small",
      //   "Border top": "border-top"
      // }),
      // "color": figma.enum('Color', {
      //   "Success": "success",
      //   "Info": "info",
      //   "Warning": "warning",
      //   "Default": "default",
      //   "Danger": "danger"
      // })
    },
    example: (props) => <Index />,
  },
);
