import React from "react";
import SplitButton from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SplitButton,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=356%3A22006",
  {
    props: {
      kind: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Tonal: "tonal",
      }),
      size: figma.enum("Size", {
        s: "s",
        base: "m",
        m: "m",
        l: "m",
      }),
    },
    example: ({ kind, size }) => (
      <SplitButton kind={kind} size={size} label="Button text">
        {/* SplitButton.Menu also available */}
        <SplitButton.Popover>
          <div>Popover content</div>
        </SplitButton.Popover>
      </SplitButton>
    ),
  },
);
