import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/nCjdO761StnkwNZHFmcrUu/Narmi-Design-System-v2?node-id=223%3A4355",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('state', {
      //   "default": "default",
      //   "today": "today",
      //   "past": "past",
      //   "selected": "selected",
      //   "disabled": "disabled",
      //   "none": "none"
      // }),
      // "hover": figma.boolean('hover')
    },
    example: (props) => <Index label={/* TODO */} placeholder={/* TODO */} />,
  },
);
