name: Check Build
on: [pull_request]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - run: |
          npm ci
          npm run build
          npx license-checker --onlyAllow "Apache-2.0"
