name: Check Build
on: [pull_request]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - run: |
          npm ci
          npm run build

  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Run npm install
        run: npm install
      - name: Check licenses
        uses: tangro/actions-license-check@v1.0.14
        with:
          allowed-licenses: 'MIT; ISC; Apache-2.0;'
