# Chromatic visual tests to run on PRs targeting `main`
name: 'Chromatic PR Checks'
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_relevant_changes: ${{ steps.changes.outputs.has_changes }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Check for relevant changes
        id: changes
        run: |
          # Get the base branch (main) and check for changes in src/ and tokens/
          git fetch origin main:main
          if git diff --name-only main...HEAD | grep -E '^(src/|tokens/)'; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Found relevant changes in src/ or tokens/"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No relevant changes found in src/ or tokens/"
          fi

  run_chromatic:
    needs: check_changes
    outputs:
      changeCount: ${{ steps.chromatic_step.outputs.changeCount }}
      buildUrl: ${{ steps.chromatic_step.outputs.buildUrl }}
      storybookUrl: ${{ steps.chromatic_step.outputs.storybookUrl }}
    if: needs.check_changes.outputs.has_relevant_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --loglevel=warn

      - name: Build
        run: npm run build && npm run build-storybook

      - name: Chromatic
        id: chromatic_step
        uses: chromaui/action@d0795df816d05c4a89c80295303970fddd247cce
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false # fail workflow if changes detected
          autoAcceptChanges: false
          buildScriptName: ''
          storybookBuildDir: './storybook-static'
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref }} # Helps Chromatic identify the correct branch

  post_chromatic_comment:
    name: Post Chromatic Comment
    runs-on: ubuntu-latest
    needs: [check_changes, run_chromatic]
    if: needs.check_changes.outputs.has_relevant_changes == 'true'
    steps:
      - name: Log run_chromatic job outputs
        run: echo "${{ toJson(needs.run_chromatic.outputs) }}"

      - name: Comment Storybook URL and diff status in PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # 3.0.1
        with:
          pr_number: ${{ github.event.pull_request.number }}
          mode: recreate
          comment_tag: chromatic-results
          message: |
            ${{ needs.run_chromatic.outputs.changeCount > '0' && format('## 🚨 Found {0} visual changes that require your attention!', needs.run_chromatic.outputs.changeCount) || '' }}
            ${{ needs.run_chromatic.outputs.changeCount <= '0' && format('## ✅ No visual changes detected') || ''}}
            ${{ format('[View Chromatic Build]({0})', needs.run_chromatic.outputs.buildUrl || needs.run_chromatic.outputs.chromatic_url) || '' }}

            ## 📘 Storybook preview
            [View Storybook preview](<${{ needs.run_chromatic.outputs.storybookUrl }}>)

            ---
            <sub>This PR is posted and updated automatically by the `Chromatic` action</sub>

  chromatic_status:
    name: Chromatic Status
    runs-on: ubuntu-latest
    needs: [check_changes, run_chromatic]
    if: always()
    steps:
      - name: Set status based on changes
        run: |
          if [ "${{ needs.check_changes.outputs.has_relevant_changes }}" = "true" ]; then
            if [ "${{ needs.run_chromatic.result }}" = "success" ]; then
              echo "Chromatic checks passed"
              exit 0
            else
              echo "Chromatic checks failed"
              exit 1
            fi
          else
            echo "No relevant changes detected, skipping Chromatic checks"
            exit 0
          fi
