name: Chromatic
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'src/**'
      - 'tokens/src/**'

jobs:
  run_chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    outputs: # required by commenting job below
      storybookUrl: ${{ steps.chromatic.outputs.storybookUrl }}
      buildUrl: ${{ steps.chromatic.outputs.buildUrl }}
      changeCount: ${{ steps.chromatic.outputs.changeCount }}
      chromatic_url: ${{ steps.chromatic.outputs.url }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --loglevel=warn

      - name: Chromatic (build, publish, and run checks)
        id: chromatic
        uses: chromaui/action@latest
        with:
          # <https://www.chromatic.com/docs/configure/#options>
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false
          autoAcceptChanges: "main"

      - name: Debug Chromatic Outputs (Optional)
        if: always()
        run: |
          echo "Chromatic Outputs: ${{ toJSON(steps.chromatic.outputs) }}"

  post_chromatic_comment:
    name: Post Chromatic Comment
    runs-on: ubuntu-latest
    needs: run_chromatic
    if: always()
    steps:
      - name: Comment Storybook URL and diff status in PR
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # 2.5.0
        with:
          pr_number: ${{ github.event.pull_request.number }}
          mode: recreate
          comment_tag: chromatic-results
          message: |
            # Chromatic Checks

            ${{ needs.run_chromatic.outputs.changeCount > '0' && format('## 🚨 Found {0} visual changes that require your attention!', needs.run_chromatic.outputs.changeCount) || '' }}
            ${{ needs.run_chromatic.outputs.changeCount > '0' && format('[View changes]({0})', needs.run_chromatic.outputs.buildUrl || needs.run_chromatic.outputs.chromatic_url) || '' }}
            ${{ needs.run_chromatic.outputs.changeCount <= '0' && '## ✅ No visual changes detected' }}

            ## 📘 Storybook preview
            [View Storybook preview](<${{ needs.run_chromatic.outputs.storybookUrl }}>)

            <sub>This PR is posted and updated automatically by the `Chromatic` action</sub>

