# Chromatic visual tests to run on PRs targeting `main`
name: 'Chromatic PR Checks'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tokens/**'

jobs:
  run_chromatic:
    outputs:
      changeCount: ${{ steps.chromatic_step.outputs.changeCount }}
      buildUrl: ${{ steps.chromatic_step.outputs.buildUrl }}
      storybookUrl: ${{ steps.chromatic_step.outputs.storybookUrl }}
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --loglevel=warn

      - name: Build
        run: npm run build && npm run build-storybook

      - name: Chromatic
        uses: chromaui/action@latest
        id: chromatic_step
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false # fail workflow if changes detected
          autoAcceptChanges: false
          buildScriptName: ''
          storybookBuildDir: './storybook-static'
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref }} # Helps Chromatic identify the correct branch

  post_chromatic_comment:
    name: Post Chromatic Comment
    runs-on: ubuntu-latest
    needs: run_chromatic
    if: always()
    steps:
      - name: Log run_chromatic job outputs
        run: echo "${{ toJson(needs.run_chromatic.outputs) }}"

      - name: Comment Storybook URL and diff status in PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # 3.0.1
        with:
          pr_number: ${{ github.event.pull_request.number }}
          mode: recreate
          comment_tag: chromatic-results
          message: |
            ${{ needs.run_chromatic.outputs.changeCount > '0' && format('## 🚨 Found {0} visual changes that require your attention!', needs.run_chromatic.outputs.changeCount) || '' }}
            ${{ needs.run_chromatic.outputs.changeCount <= '0' && format('## ✅ No visual changes detected') || ''}}
            ${{ format('[View Chromatic Build]({0})', needs.run_chromatic.outputs.buildUrl || needs.run_chromatic.outputs.chromatic_url) || '' }}

            ## 📘 Storybook preview
            [View Storybook preview](<${{ needs.run_chromatic.outputs.storybookUrl }}>)

            ---
            <sub>This PR is posted and updated automatically by the `Chromatic` action</sub>