# Updates snapshots in chromatic, using latest `main` as basleline
name: 'Chromatic Snapshot Baseline'
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  chromatic_update_baseline:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts --loglevel=warn

      - name: Build
        run: npm run build && npm run build-storybook

      - name: Auto-accept chromatic snapshots from `main`
        uses: chromaui/action@e3eb8ec36101d8f0253c7c3ae66e5a2b4e2197ba # v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
          exitZeroOnChanges: false
          buildScriptName: ''
          storybookBuildDir: './storybook-static'
