name: Github Pages
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Build static storybook
        run: |
          npm ci -loglevel=warn
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          branch: gh-pages
          folder: storybook-static
