name: Github Pages
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v4
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org

      - name: Build static storybook
        run: |
          npm ci --ignore-scripts --loglevel=warn
          npm run build
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          branch: gh-pages
          folder: storybook-static
