name: Vitest
permissions:
  contents: read
on: [pull_request]
jobs:
  Run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Cache build
        id: build-cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: dist
          key: build-${{ hashFiles('src/**', 'package-lock.json') }}

      - name: Build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: npm run build

      - name: Vitest
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          npm run test
